### ISSUE TITLE
semi-colon separated values for each cell

### ISSUE THREAD

**Issue by dcruz5h** [vangalenlab/MAESTER-2021#1]
With your permission, I wanted to run the GoT.QC.R script on the IronThrone GoT.summTable.concat.txt output table of my experiment. 
Unfortunately, I got an error 
Error: all(unlist(lapply(summtable.ls, function(x) length(unique(apply(x,  .... is not TRUE

It seems that your code check that all cell barcodes have a semi colon separated value. 
Do you know why would the IronThrone output table does not meet this criteria ? if so how would you fix this problem.

**Comment by petervangalen** [comment]
Can you share (part of) the GoT summary table so that I can reproduce the error?

**Comment by dcruz5h** [comment]
[myGoT.summTable.concat.umi_collapsed.txt](https://github.com/petervangalen/MAESTER-2021/files/8140553/myGoT.summTable.concat.umi_collapsed.txt)
[myGoT.summTable.concat.txt](https://github.com/petervangalen/MAESTER-2021/files/8140560/myGoT.summTable.concat.txt)

Here is the output of GoT 2.1
GoT gives two files, but only myGoT.summTable.concat.umi_collapsed.txt has the calls. Which is the one I used for GoT.QC.R . Which table would you use for GoT.QC.R ? 
myGoT.summTable.concat.umi_collapsed.txt gives this error when loading:
 Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec,  : 
  line 459 did not have 9 elements

myGoT.summTable.concat.umi_collapsed.txt gives this error when used: 
Error: all(unlist(lapply(summtable.ls, function(x) length(unique(apply(x, .... is not TRUE

Thank you for all the help. I really appreciate it. 
best

**Comment by petervangalen** [comment]
I was able to reproduce the error. In GoT_QC.R, the summary table is made into a list (every row becomes an element). Line 44 checks (for every element in the list) if every column has the same number of semicolon-separated values:
```
stopifnot( all(unlist( lapply(summtable.ls, function(x) length( unique( apply(x, 2, function(x) length(unlist(strsplit(x, split = ";")))))))) == 1) )
```
If this is not the case, you get the error, because this indicates an unexpected structure of the summary table.

I attached a summary table for the TET2.S792X mutation (TET2.2340.summTable.txt). When I run GoT_QC.R as follows:
```
dir.ch <- "~/maester_summtable/"
summtable <- "~/maester_summtable/TET2.2340.summTable.txt"
sample.ch <- "BPDCN712"
gene.name <- "TET2"

system(paste("Rscript ~/DropboxMGB/Projects/Maester/AnalysisPeter/MAESTER-2021/Pre-processing/GoT_QC.R", dir.ch, summtable, sample.ch, gene.name))
```
The output is TET2.QC.pdf and TET2.2340.FilteredCells.txt (attached).

I do not know why your input is different but hopefully this will help you find out.

[TET2.2340.FilteredCells.txt](https://github.com/petervangalen/MAESTER-2021/files/8153308/TET2.2340.FilteredCells.txt)
[TET2.2340.summTable.txt](https://github.com/petervangalen/MAESTER-2021/files/8153309/TET2.2340.summTable.txt)
[TET2.QC.pdf](https://github.com/petervangalen/MAESTER-2021/files/8153311/TET2.QC.pdf)
